name: Use Matriz for JSON

on:
  workflow_dispatch:
    inputs:
      environment:
        description: What environment to use for the setup?
        required: true
        default: 'XXX'
        #type: environment

defaults:
  run:
    shell: bash
    working-directory: ./.github
    
jobs:
  setup:
    name: Capture JSON files
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.matrix.outputs.environments }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check files
      run: |
        pwd
        echo "environments=$( jq -c -n --arg diff "$(ls *.json)" '$diff | split("\n") | map(select(.) | .) | unique' )"

    - name: Generate matrix
      id: matrix
      run: |
        echo "environments=$( jq -c -n --arg diff "$(ls *.json)" '$diff | split("\n") | map(select(.) | .) | unique' )" >> $GITHUB_OUTPUT

  process-json:
    needs: 
    - setup
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.setup.outputs.environments) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: cat ${{ matrix.environment }} before
      run: cat ${{ matrix.environment }}

    - name: sed ${{ matrix.environment }} 
      run: sed -i "s/color/${{ inputs.environment }}/g" ${{ matrix.environment }}  

    - name: cat ${{ matrix.environment }} after
      run: cat ${{ matrix.environment }}  

    - name: Deploy to Grafans
        env:
          GRAFANA_URL: 'https://dev-grafana.example.com'
          ENVIRONMENT: dev
        run: |
          curl -X GET \
            -H "Content-Type: application/json" \
            -d ${{ matrix.environment }} \
            https://api.country.is/"  
