name: Use Matriz for JSON

on:
  push:
    branches:
    - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash
    working-directory: ./.github
    
jobs:
  setup:
    name: Set JSON files
    runs-on: ubuntu-latest
    outputs:
      jsonfiles: ${{ steps.matrix.outputs.jsonfiles }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check files
      run: |
        pwd
        echo "jsonfiles=$( jq -c -n --arg diff "$(ls *.json)" '$diff | split("\n") | map(select(.) | .) | unique' )"

    - name: Generate matrix
      id: matrix
      run: |
        echo "jsonfile=$( jq -c -n --arg diff "$(ls *.json)" '$diff | split("\n") | map(select(.) | .) | unique' )" >> $GITHUB_OUTPUT

  process-json:
    needs: 
    - setup
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jsonfiles: ${{ fromJSON(needs.setup.outputs.jsonfiles) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: cat ${{ matrix.jsonfiles }}
      run: cat ${{ matrix.jsonfiles }}
     
