name: PR Merged Notification with File Content

on:
 pull_request:
    types: [closed]

jobs:
  get_file_content:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.get-content.outputs.content }}
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Get File Content
        id: get-content
        run: |
          echo "::set-output name=content::$(cat my_file.txt)"

  notify-slack:
   if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      needs: [get_file_content, parse-content] 
      steps:
        - name: Slack Notification (App)
          run: |
            echo "Repository ${{ steps.parse-content.outputs.repo_name }} has been created by ${{ steps.parse-content.outputs.creator }} at ${{ steps.parse-content.outputs.timestamp }}"
