name: PR Merged Notification with File Content
on:
  pull_request:
    types: [closed]
jobs:
  get-file-content:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.get-content.outputs.content }}
      file_exists: ${{ steps.check-file.outputs.exists }}
    steps:
      - name: Checkout Target Branch 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }} 

      - name: Check if File Exists
        id: check-file
        run: |
          if [[ -f "dir1/dir2/projects.txt" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "::warning::File 'dir1/dir2/projects.txt' not found. Skipping notification."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Get Last Line of File
        id: get-content
        # Run only if file_exists output is 'true'
        if: steps.check-file.outputs.exists == 'true'
        run: |
          CONTENT=$(tail -n 1 terraform-deployments/external-project-roles/projects.txt)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT 

  parse-content:
    # Run only if file_exists output is 'true'
    if: steps.check-file.outputs.exists == 'true'
    runs-on: ubuntu-latest
    needs: get-file-content
    outputs:
      repo_name: ${{ steps.parse-content.outputs.repo_name }}
      creator: ${{ steps.parse-content.outputs.creator }}
      timestamp: ${{ steps.parse-content.outputs.timestamp }}
    steps:
      - name: Parse File Content
        id: parse-content
        run: |
          LAST_LINE="${{ needs.get-file-content.outputs.file_content }}"
          TIMESTAMP="${LAST_LINE%%,*}" 
          REPO_NAME="${LAST_LINE#*,}"   
          REPO_NAME="${REPO_NAME%%,*}" 
          CREATOR="${LAST_LINE##*,}"
          CREATOR="${CREATOR##*/}"
          echo "lastline=$LAST_LINE"
          echo "timestamp=$TIMESTAMP"
          echo "repo_name=$REPO_NAME"
          echo "creator=$CREATOR"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "creator=$CREATOR" >> $GITHUB_OUTPUT

  notify-slack:
    if: steps.check-file.outputs.exists == 'true'
    runs-on: ubuntu-latest
    needs: [get-file-content, parse-content] 
    steps:
      - name: Slack Notification (App)
        run: |
          echo "Repository ${{ needs.parse-content.outputs.repo_name }} has been created by ${{ needs.parse-content.outputs.creator }} at ${{ needs.parse-content.outputs.timestamp }}" 
          
