name: PR Merged Notification with File Content
on:
  pull_request:
    types: [closed]
jobs:
  get-file-content:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.get-content.outputs.content }}
      file_exists: ${{ steps.check-file.outputs.exists }}
      branch_in_title: ${{ steps.check-branch-name.outputs.branch_in_title }}
    steps:
      - name: Checkout Target Branch 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }} 

      - name: Check Branch Name in PR Title
        id: check-branch-name
        run: |
          if echo "${{ github.event.pull_request.title }}" | grep -q "${{ github.event.pull_request.head.ref }}" ; then
            echo "branch_in_title=true"
            echo "branch_in_title=true" >> $GITHUB_OUTPUT
          else
            echo "::warning::Branch name not found in PR title. Skipping notification."
            echo "branch_in_title=false"
            echo "branch_in_title=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if File Exists
        id: check-file
        if: steps.check-branch-name.outputs.branch_in_title == 'true'
        run: |
          if [[ -f "terraform-deployments/external-project-roles/projects.txt" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "exists=true"
          else
            echo "::warning::File 'terraform-deployments/external-project-roles/projects.txt' not found. Skipping notification."
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "exists=false"
          fi
        
      - name: Get Last Line of File
        id: get-content
        # Run only if file_exists output is 'true'
        if: steps.check-file.outputs.exists == 'true'
          && steps.check-branch-name.outputs.branch_in_title == 'true'
        run: |
          CONTENT=$(tail -n 1 terraform-deployments/external-project-roles/projects.txt)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT 

  parse-content:
    # Run only if file_exists output is 'true'
    if: needs.get-file-content.outputs.file_exists == 'true'
      && needs.get-file-content.outputs.branch_in_title == 'true'
    runs-on: ubuntu-latest
    needs: get-file-content
    outputs:
      repo_name: ${{ steps.parse-content.outputs.repo_name }}
      creator: ${{ steps.parse-content.outputs.creator }}
      timestamp: ${{ steps.parse-content.outputs.timestamp }}
      text_ok: ${{ steps.parse-content.outputs.text_ok }}
    steps:
      - name: Parse File Content
        id: parse-content
        run: |
          LAST_LINE="${{ needs.get-file-content.outputs.file_content }}"
          TIMESTAMP="${LAST_LINE%%,*}" 
          REPO_NAME="${LAST_LINE#*,}"   
          REPO_NAME="${REPO_NAME%%,*}" 
          CREATOR="${LAST_LINE##*,}"
          CREATOR="${CREATOR##*/}"
          echo "lastline=$LAST_LINE"
          echo "timestamp=$TIMESTAMP"
          echo "repo_name=$REPO_NAME"
          echo "creator=$CREATOR"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "creator=$CREATOR" >> $GITHUB_OUTPUT
          
      - name: Check values are not blank    
        id: check-values
        run: |
          if [[ -z "$TIMESTAMP" || -z "$REPO_NAME" || -z "$CREATOR" ]]; then
            echo "::warning::One or more required values are blank. Skipping notification."
            echo "valid_ok=false" >> $GITHUB_OUTPUT
            echo "valid_ok=false"
          else
            echo "valid_ok=true" >> $GITHUB_OUTPUT
            echo "valid_ok=true"
          fi

  notify-slack:
    if: needs.get-file-content.outputs.file_exists == 'true'
      && needs.get-file-content.outputs.branch_in_title == 'true'
      && needs.parse-content.outputs.valid_ok == 'true'
    runs-on: ubuntu-latest
    needs: [get-file-content, parse-content] 
    steps:
      - name: Slack Notification (App)
        run: |
          echo "Repository ${{ needs.parse-content.outputs.repo_name }} has been created by ${{ needs.parse-content.outputs.creator }} at ${{ needs.parse-content.outputs.timestamp }}" 
          
