name: Get PR Release Notes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  extract_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (optional, but good practice)
        uses: actions/checkout@v4

      - name: Extract Release Notes Content (No Trim)
        id: extract_notes # Give this step an ID to access its outputs
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          echo "-------------"
          echo $PR_BODY
          echo "-------------"
          
          # Define the marker you're looking for
          MARKER="## Release Notes"
          EXTRACTED_CONTENT=$(echo -e "$PR_BODY" | awk -v marker="$MARKER" 'f{print}; $0 == marker{f=1}')
          # If nothing was extracted (e.g., the marker wasn't found, or no content after), default to empty.
          if [ -z "$EXTRACTED_CONTENT" ]; then
            echo "No content found after '## Release Notes' or marker not present."
            FINAL_NOTES=""
          else
            FINAL_NOTES="$EXTRACTED_CONTENT"
          fi
          echo "Extracted Content (Raw):"
          echo "$FINAL_NOTES"

          # Set the extracted content as a step output
          echo "release_notes_content<<EOF" >> $GITHUB_OUTPUT
          echo "$FINAL_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Display Extracted Notes (from step output)
        run: |
          echo "--- Final Release Notes from Output (Raw) ---"
          echo "${{ steps.extract_notes.outputs.release_notes_content }}"
          echo "-------------------------------------"
